name: BuildPdf
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - name: GitHub Action for LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: resume.tex
                
